export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_IN_USER = "LOGIN_IN_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const ADD_USER_TO_BASKET = "ADD_USER_TO_BASKET";
export const DELETE_USER_FROM_BIN = "DELETE_USER_FROM_BIN";
export const RESTORE_USER_FROM_BIN = "RESTORE_USER_FROM_BIN";
export const GET_PREMIUM_ACCESS = "GET_PREMIUM_ACCESS";