// <auto-generated />
namespace Dynamic_IP_Address_Service_Server.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addtokentable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtokentable));
        
        string IMigrationMetadata.Id
        {
            get { return "201708291234023_add token table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
