USE Company

INSERT INTO Department (Title, Address) VALUES ('rockwell collins', '1780 harper');
INSERT INTO Department (Title, Address) VALUES ('nrg energyorporated', '5364 columbus');
INSERT INTO Department (Title, Address) VALUES ('kb home', '919 summerdale');
INSERT INTO Department (Title, Address) VALUES ('nustar energy', '3719 kennedy cumberland av');
INSERT INTO Department (Title, Address) VALUES ('aon', '5123 arcade');
INSERT INTO Department (Title, Address) VALUES ('hollyfrontier2 corporation', '1748 spaulding');
INSERT INTO Department (Title, Address) VALUES ('cincinnati financial corporation', '4943 zemke');
INSERT INTO Department (Title, Address) VALUES ('brocade communications systems', '8884 59th');
INSERT INTO Department (Title, Address) VALUES ('the scotts company, ', '2636 grenshaw');
INSERT INTO Department (Title, Address) VALUES ('allstate2', '236 gladys');
INSERT INTO Department (Title, Address) VALUES ('plexus corp', '9878 66th');
INSERT INTO Department (Title, Address) VALUES ('fortune brands', '1767 le mai');
INSERT INTO Department (Title, Address) VALUES ('huntsman international ', '2648 waterside');
INSERT INTO Department (Title, Address) VALUES ('snap-on tools', '4262 ancona');
INSERT INTO Department (Title, Address) VALUES ('republic services', '7500 fargo');
INSERT INTO Department (Title, Address) VALUES ('pinnacle west capital corporation', '2784 urban');
INSERT INTO Department (Title, Address) VALUES ('ambac financial group', '2265 midway park');
INSERT INTO Department (Title, Address) VALUES ('sentry insurance', '168 baltimore');
INSERT INTO Department (Title, Address) VALUES ('the phoenix companies', '6893 nokomis');
INSERT INTO Department (Title, Address) VALUES ('enersys', '5344 postoffice');
INSERT INTO Department (Title, Address) VALUES ('american water', '9829 edens');
INSERT INTO Department (Title, Address) VALUES ('abbott laboratories', '4962 grover');
INSERT INTO Department (Title, Address) VALUES ('mastec', '2249 burkhardt');
INSERT INTO Department (Title, Address) VALUES ('healthspring', '2885 eisenhower ib kennedy ob');
INSERT INTO Department (Title, Address) VALUES ('synnex corporation', '1722 packers');
INSERT INTO Department (Title, Address) VALUES ('interpublic group of companies', '1117 michigan lower');
INSERT INTO Department (Title, Address) VALUES ('sungard', '5749 96th');
INSERT INTO Department (Title, Address) VALUES ('tiffany & co', '1693 i55 kedzie av');
INSERT INTO Department (Title, Address) VALUES ('berry plastics corporation', '2316 63rd');
INSERT INTO Department (Title, Address) VALUES ('cerner corporation', '8905 lloyd');
INSERT INTO Department (Title, Address) VALUES ('ashland', '6533 lyon');
INSERT INTO Department (Title, Address) VALUES ('moog', '8891 river loft');
INSERT INTO Department (Title, Address) VALUES ('granite construction', '3785 dan ryan ib eisenhower ob');
INSERT INTO Department (Title, Address) VALUES ('biogen idec', '1726 spokane');
INSERT INTO Department (Title, Address) VALUES ('oge energy corp', '4788 evelyn');
INSERT INTO Department (Title, Address) VALUES ('wyndham worldwide corp', '3647 la salle dr');
INSERT INTO Department (Title, Address) VALUES ('eaton corporation', '2951 schilling');
INSERT INTO Department (Title, Address) VALUES ('harsco corporation', '2581 dan ryan 47th st');
INSERT INTO Department (Title, Address) VALUES ('ingles markets', '7481 dekalb');
INSERT INTO Department (Title, Address) VALUES ('ralph lauren corporation', '7655 park');
INSERT INTO Department (Title, Address) VALUES ('silgan holdings', '4638 dekoven');
INSERT INTO Department (Title, Address) VALUES ('massachusetts mutual financial group', '8482 clifton');
INSERT INTO Department (Title, Address) VALUES ('cummins', '7561 givins');
INSERT INTO Department (Title, Address) VALUES ('knights of columbus', '2073 riverview');
INSERT INTO Department (Title, Address) VALUES ('caci international', '492 mann');
INSERT INTO Department (Title, Address) VALUES ('allstate', '6478 argyle');
INSERT INTO Department (Title, Address) VALUES ('lennox international', '4550 wallace');
INSERT INTO Department (Title, Address) VALUES ('level', '702 ridge');
INSERT INTO Department (Title, Address) VALUES ('precision castparts corp', '2223 canfield av jfk');
INSERT INTO Department (Title, Address) VALUES ('whole2 foods market', '5223 dewitt');
INSERT INTO Department (Title, Address) VALUES ('exide technologies', '7301 lothair');
INSERT INTO Department (Title, Address) VALUES ('lincoln electric company', '4654 lake calumet harbor ent');
INSERT INTO Department (Title, Address) VALUES ('nucor corporation', '1012 north shore channel');
INSERT INTO Department (Title, Address) VALUES ('crown castle international corp', '9892 hickory');
INSERT INTO Department (Title, Address) VALUES ('xerox', '3328 normandy');
INSERT INTO Department (Title, Address) VALUES ('gamestop corp', '2326 normal');
INSERT INTO Department (Title, Address) VALUES ('iron mountain', '8812 orange');
INSERT INTO Department (Title, Address) VALUES ('kar auction services', '4065 newgard');
INSERT INTO Department (Title, Address) VALUES ('air products and chemicals2', '6629 dan ryan 35th st');
INSERT INTO Department (Title, Address) VALUES ('air products and chemicals', '3565 cta 69th st');
INSERT INTO Department (Title, Address) VALUES ('bank of america', '4560 payne');
INSERT INTO Department (Title, Address) VALUES ('avery dennison corporation', '8495 beverly glen');
INSERT INTO Department (Title, Address) VALUES ('invacare corporation', '640 miller');
INSERT INTO Department (Title, Address) VALUES ('unified grocers', '920 zemke');
INSERT INTO Department (Title, Address) VALUES ('cinemark usa', '5098 maplewood');
INSERT INTO Department (Title, Address) VALUES ('tyson foods', '9816 upperlevelt2');
INSERT INTO Department (Title, Address) VALUES ('the mosaic company', '2547 riverside');
INSERT INTO Department (Title, Address) VALUES ('briggs & stratton corporation', '5751 lehmann');
INSERT INTO Department (Title, Address) VALUES ('toys r us', '5366 dewitt');
INSERT INTO Department (Title, Address) VALUES ('solutia', '1141 pope john paul ii');
INSERT INTO Department (Title, Address) VALUES ('cooper standard', '6811 clifton');
INSERT INTO Department (Title, Address) VALUES ('alliant techsystems', '5082 hunt');
INSERT INTO Department (Title, Address) VALUES ('kbr', '6693 ozark');
INSERT INTO Department (Title, Address) VALUES ('r.r. donnelley & sons co', '8612 early');
INSERT INTO Department (Title, Address) VALUES ('campbell soup company', '5914 i57 bishop ford expy');
INSERT INTO Department (Title, Address) VALUES ('whole foods market', '4156 berenice');
INSERT INTO Department (Title, Address) VALUES ('c. r. bardorporated', '9294 hollywood');
INSERT INTO Department (Title, Address) VALUES ('erie insurance group', '7122 merrion');
INSERT INTO Department (Title, Address) VALUES ('owens & minor', '8528 wallace');
INSERT INTO Department (Title, Address) VALUES ('ametek', '9590 serbian');
INSERT INTO Department (Title, Address) VALUES ('ingram micro', '9965 shapland');
INSERT INTO Department (Title, Address) VALUES ('dollar thrifty automotive group', '7976 lakefront');
INSERT INTO Department (Title, Address) VALUES ('kohl''s corporation', '9955 31st');
INSERT INTO Department (Title, Address) VALUES ('medical mutual of ohio', '8930 sutton');
INSERT INTO Department (Title, Address) VALUES ('western union company', '7676 james m rochford');
INSERT INTO Department (Title, Address) VALUES ('bon-ton stores', '5432 jonquil');
INSERT INTO Department (Title, Address) VALUES ('staples financial', '3943 redwood');
INSERT INTO Department (Title, Address) VALUES ('hollyfrontier corporation', '8488 dearborn');
INSERT INTO Department (Title, Address) VALUES ('cummins engine', '9011 independence');
INSERT INTO Department (Title, Address) VALUES ('lincoln financial group', '8723 holden');
INSERT INTO Department (Title, Address) VALUES ('heartland payment systemsorporated', '4518 asher');
INSERT INTO Department (Title, Address) VALUES ('arthur j. gallagher & co', '3237 young');
INSERT INTO Department (Title, Address) VALUES ('united rentals', '4858 wilmot');
INSERT INTO Department (Title, Address) VALUES ('hsn', '5076 st michaels');
INSERT INTO Department (Title, Address) VALUES ('dell', '5115 deming');
INSERT INTO Department (Title, Address) VALUES ('dean foods company', '2628 patterson');
INSERT INTO Department (Title, Address) VALUES ('sandisk corporation', '9652 la salle dr');
INSERT INTO Department (Title, Address) VALUES ('mdu resources group', '65 napoleon');
INSERT INTO Department (Title, Address) VALUES ('dentsply international', '8568 kennedy');
