USE Company;

INSERT INTO Job (Position, MinSalary) VALUES ('Clinical Specialist', '$1442.72');
INSERT INTO Job (Position, MinSalary) VALUES ('Budget/Accounting Analyst III', '$1909.40');
INSERT INTO Job (Position, MinSalary) VALUES ('Accountant III', '$1194.90');
INSERT INTO Job (Position, MinSalary) VALUES ('Senior Cost Accountant', '$955.04');
INSERT INTO Job (Position, MinSalary) VALUES ('Occupational Therapist', '$1198.68');
INSERT INTO Job (Position, MinSalary) VALUES ('Automation Specialist III', '$850.67');
INSERT INTO Job (Position, MinSalary) VALUES ('Mechanical Systems Engineer', '$1932.80');
INSERT INTO Job (Position, MinSalary) VALUES ('Marketing Assistant', '$2911.27');
INSERT INTO Job (Position, MinSalary) VALUES ('Social Worker', '$2545.86');
INSERT INTO Job (Position, MinSalary) VALUES ('Actuary', '$60.72');
INSERT INTO Job (Position, MinSalary) VALUES ('Social Worker', '$1781.19');
INSERT INTO Job (Position, MinSalary) VALUES ('Programmer Analyst III', '$2542.14');
INSERT INTO Job (Position, MinSalary) VALUES ('Actuary', '$1654.24');
INSERT INTO Job (Position, MinSalary) VALUES ('Physical Therapy Assistant', '$1898.68');
INSERT INTO Job (Position, MinSalary) VALUES ('Senior Sales Associate', '$752.41');
INSERT INTO Job (Position, MinSalary) VALUES ('Clinical Specialist', '$489.20');
INSERT INTO Job (Position, MinSalary) VALUES ('Programmer Analyst I', '$1943.41');
INSERT INTO Job (Position, MinSalary) VALUES ('Account Coordinator', '$1327.25');
INSERT INTO Job (Position, MinSalary) VALUES ('Assistant Media Planner', '$685.39');
INSERT INTO Job (Position, MinSalary) VALUES ('Senior Sales Associate', '$2927.57');
INSERT INTO Job (Position, MinSalary) VALUES ('Programmer IV', '$1779.69');
INSERT INTO Job (Position, MinSalary) VALUES ('Human Resources Manager', '$2550.25');
INSERT INTO Job (Position, MinSalary) VALUES ('Graphic Designer', '$1982.12');
INSERT INTO Job (Position, MinSalary) VALUES ('Geologist II', '$241.39');
INSERT INTO Job (Position, MinSalary) VALUES ('Marketing Assistant', '$1580.48');
INSERT INTO Job (Position, MinSalary) VALUES ('Media Manager III', '$2739.24');
INSERT INTO Job (Position, MinSalary) VALUES ('Compensation Analyst', '$497.28');
INSERT INTO Job (Position, MinSalary) VALUES ('Quality Control Specialist', '$115.40');
INSERT INTO Job (Position, MinSalary) VALUES ('Safety Technician III', '$1165.23');
INSERT INTO Job (Position, MinSalary) VALUES ('Electrical Engineer', '$918.43');
