export const UNDEF_CODE = 101;
export const REGISTER_LOGIN_OR_EMAIL_UNAVAILABLE = 110;
export const INCORRECT_LOGIN_OR_PASSWORD = 111;
export const DOMAIN_UNAVAILABLE = 140;
export const INCORRECT_IP_ADDRESS = 141;
