export const GET_ALL_USERS = "GET_USERS";
export const GET_ALL_USERS_IN_BIN = "GET_ALL_USERS_IN_BIN";
export const GET_PREMIUM_ACCESS = "GET_PREMIUM_ACCESS";
export const MOVE_TO_BIN = "MOVE_TO_BIN";
export const DELETE_USER_FROM_BIN = "DELETE_USER_FROM_BIN";
export const RESTORE_USER_FROM_BIN = "RESTORE_USER_FROM_BIN";